### PR TITLE
add support to JSON values

### LINKED ISSUE #8: Multiline JSON produces unescaped env var
This code:
```js
stringify({ JSON_MULTILINE: JSON.stringify({ a: 'b', c: 'd' }, null, 2) })
```

Produces:
```env
JSON_MULTILINE={
  \"a\": \"b\",
  \"c\": \"d\"
}
```

---

As you can see, an unescaped multi line env var is created, which should not be allowed

### PR DESCRIPTION
**Pull request by zvictor**
fix #8

### CODE REVIEW

**Comment by zvictor** [comment]
🙂

**Comment by compwright** [comment]
Thank you, but we're not supporting this. You should never have a multi-line value (JSON or otherwise) in an environment variable. It's problematic for many reasons. Just don't do it.

**Comment by zvictor** [comment]
Thanks for reviewing, @compwright. You definitely have a point there! Multi-line value is an anti-pattern and I am not personally in favour of them.

However, a tool I was using was creating them for me, which has lead to all sorts of bugs that were hard to track in my application.
Of course such tool should be fixed instead of yours, but let me be the devil's advocate here and throw some food for thoughts:

* If we can make dotenv-stringify more flexible and permissive with this PR, what is the trade-off?
* If there is no significant trade-off, how is the current implementation of dotenv-stringify better without the proposed PR?

**Comment by compwright** [comment]
To answer your question, the trade-off is that if a behavior is introduced into this package then someone will come to rely on it. Or if not, I will be responsible for maintaining code that no one is using. In this instance, "flexible and permissive" is not a good thing. It encourages use of an anti-pattern, and it lays land mines that will blow up at unexpected times.

The .env file format is not designed to be an all-purpose format for storing all types of data. It is a format from the Linux OS designed for storing environment variables specifically. There are all sorts of problems with the various shells, the env command, and the various ways environment variables can be used in shell scripts that break in unexpected ways when the value has a newline.

That's why I really don't want to include explicit support for a behavior that is guaranteed to break something, somewhere.

Besides, even the JSON serialization of objects is beyond the scope of this package and really should be removed altogether from this library.

**Comment by zvictor** [comment]
I am not sure I agree with you but I definetely appreciate your thoughts on this matter and I respect your position.
You have good points, indeed.

Thank you for sharing! 🤝

**Pull request closed without merging**
